moderntribe/tampermonkey-scripts

README.md, qa-headers.user.js
=> This is a re-working of PR #4 that adds QA heading styles

README.md, central-collapsable-sidebar.user.js
Add option to have a collapsable sidebar and make it available only when required
=> Add script to have a collapsabe sidebar on central

premium-forum-extras.js
You can see the details in the description part of the file.
=> Helpful stuff for the premium support forum back-end

premium-forum-extras.js
Restructured the end part a bit. 
Added Eventbrite Tickets and Image Widget Plus.
Updated plugin version numbers after MR 18.05
=> Updated plugin version numbers after MR 18.05

premium-forum-extras.js
Updated plugin version numbers after MR 18.06
=> Updated plugin version numbers

premium-forum-extras.js
@andrasguseo 
Well that was weird... part of it went to this PR and part got directly committed via https://github.com/moderntribe/tampermonkey-scripts/commit/1c70ce504475b65fcd4e0bd70168950274c49e5f
Basically you can decline this PR and leave that commit as-is or if you don't like something about it then undo that commit or just commit anew over it.
Sorry for the mixup!
=> Easy tweaks

dotorg-helper.user.js, dotorg-hider.user.js
Added missing users ggwicz and jentheo.
Changed color of team last response to blue for better visibility.
Older than a month and team last voice will be yellow & visible to signal closing action.
=> Dotorg updates

premium-forum-extras.js
Updated TEC and PRO version numbers after MR 18.07 released.
=> M18.07 plugin version updates

relay-for-toggl.user.js
Add support for default activity and timer text, fix duplicate elements getting added in certain cases, rename script to use .user.js so it can auto-install
=> Fix toggl container duplicate elements getting added, add defaults support

README.md, premium-forum-move-status-box.user.js, premium-forum-plugin-versions.user.js, premium-forum-private-topic.user.js, premium-forum-users-licenses.user.js
I split up the premium-forum-extras script because not everybody needs all features and it's easier to maintain them like this.
=> Split up the premium-forum-extras

premium-forum-plugin-versions.user.js
"Refactored" most of the script to allow for easier updates.
Added notes and descriptions.
Removed unused code and cleaned up a bit.
=> Major refactor

premium-forum-plugin-versions.user.js
If the users didn't have Woo or EDD in the plugin list, then the table wouldn't show.
=> Fixed a glitch when user had no ecm

premium-forum-plugin-versions.user.js
Regex added to account for the html tags if sysinfo is in the sysinfo box.
=> Update the plugin name with regex

premium-forum-collapse-convo.user.js
Made last 2 replies visible (thanks for the idea @cliffordp !)
Corrected the number of hidden replies.
Added some markup.
=> CSS fix for collapse convo

github-pr-tools-merge.js
GitHub updated some functionality, I also improved it so it wouldn't accidentally toggle code review/merge on or off.
=> Fix GitHub PR Tools (merge)

README.md, key-commands.js
=> adds a tampermonkey script to allow for key commands

key-commands.js
so Tampermonkey can auto-update
=> Add download/update link

premium-forum-plugin-versions.user.js
Updated plugin version numbers for M18.14
=> M18.14 update

dotorg-helper.user.js, dotorg-hider.user.js
=> Member update

dotorg-helper.user.js, dotorg-hider.user.js
Ali, alias tokyobiyori
Upped version number
=> Added newest support member

README.md, liveagent-plugin-versions.user.js
This is an adapted version of the premium-forum-plugin-versions.user.js script, to make it work within LiveAgent.
=> New liveagent script

liveagent-plugin-versions.user.js
Fix vertical alignment of show/hide in table cell
Enhance how container box positioning is handled on all screen sizes
=> Fixing and enhancing the hide/show function

liveagent-plugin-versions.user.js
Added the version numbers of the Feb 5 feature release of our plugins.
=> F19.01 plugin versions

liveagent-plugin-versions.user.js
... plus a new 'view more' feature.
=> G19.03 plugin versions

dotorg-helper.user.js
Updated team members who do support on .org
=> Team member update

liveagent-plugin-versions.user.js
=> Adjusted version numbers based on March hotfixes

liveagent-plugin-versions.user.js
Adjusted version numbers for G19.05
Adjusted version numbers for the hotfixes after
=> Updated with G19.05

auto-tbd.user.js, central-estimates-time-conversion.user.js, central-friendly-ui-for-multiple-pr.user.js, central-issues-kanban.user.js, central-link-pr-formatting.user.js, central-links.user.js, github-pull-prefix-removal.user.js, issue-summary.user.js, over-estimate.user.js, party-llamacorn.user.js, qa-headers.user.js, qa-testing-instructions.user.js, sticky-clocker-dropdowns.user.js
Let's make all of them consistent
=> Central URLs from HTTP to HTTPS

central-new-issue-templates.user.js
https://central.tri.be/issues/129453#note-12
=> ask for SysInfo for bugs

liveagent-clickafy-central-id.user.js
=> Correct handling of central tickets with full URL

liveagent-clickafy-central-id.user.js
The script now handles Sandbox URL as well
=> Clickafy Sandbox URL in LiveAgent

liveagent-plugin-versions.user.js
Added the new plugin version numbers to the LiveAgent Plugin Versions script
=> Updated plugin version numbers with B1913

liveagent-plugin-versions.user.js
Adjust version numbers for LA version script
=> adjust version numbers for G19.12

clocking-nag.user.js
- so that browser's login form does not appear
- added `@downloadURL` to enable automatic updates
- bumped version number
=> Don't load on Login screen

central-new-issue-templates.user.js
Update the templates to more closely match what we've been doing in Green for Scope/Testing Instructions. See https://central.tri.be/issues/132169
:ticket: https://central.tri.be/issues/135709
=> feat(central templates): Update the bug and feature templates.

jira/README.md, jira/jira-global-nav-dashboard.js
This allows me to keep the "Your Work" link as-is on the Jira Global Navigation, while also giving me access to my Dashboard with a single click from anywhere.
Screencast: http://p.tri.be/ov7Grn
🎫 [PDTOOLS-59]
[PDTOOLS-59]: https://moderntribe.atlassian.net/browse/PDTOOLS-59
=> PDTOOLS-59 Adding a Dashboard icon to the Global Nav

liveagent/liveagent-clickafy-urls.user.js
Renamed the file b/c of extended functionality and because we are moving away from Central.
Updated the download URL.
=> Renamed the file

jira/jira-mywork-hide-events.user.js
* Set up a settings part at the top
* Broke out the class name to be a setting
=> Updated class name and script

dotorg/dotorg-helper.user.js, dotorg/dotorg-hider.user.js
Added:
- MattB
- LucasB
- Rafsun
- Translations Team
Added notes on top.
Upped version number.
=> user list update
